#!/bin/bash

cd src/main/frontend
npm install --no-symlinks
npm run build
npm run start

# Verificar si npm run start se ejecutó correctamente
if [ $? -ne 0 ]; then
    echo "Error: Hubo un problema ejecutanddo 'npm run start'"
    exit 1